### PR TITLE
fix worldgenjson't caves 

### LINKED ISSUE #87: Caves Don't Spawn
## Description
***lmfao*** i forgot to fix caves

## To Reproduce

1. go in fraiya dimension
2. go in spectator mode
3. go underground
4. cry

## Expected Behavior
caves should exist

## Screenshots/Logs
wtf

## Specifications
Operating System | Minecraft Version | Mod Version
---------------- | ----------------- | -----------
Linux Ubuntu 20.04 | 1.17 | 2-SNAPSHOT

### PR DESCRIPTION
**Pull request by sylv256**
## Changelog
 - Fix cavegen

## Todo
 - [x] #87 
 - [x] Tested

### CODE REVIEW

File: src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java [hunk 1]
```diff
@@ -131,12 +131,12 @@ public boolean carve(CarverContext carverContext, LintCaveCarverConfig caveCarve
...
 	@Override
 	public boolean shouldCarve(LintCaveCarverConfig config, Random random) {
-		return false;
+		return random.nextFloat() <= config.probability;
 	}
 
 	@Override
 	protected boolean canCarveBlock(BlockState state, BlockState stateAbove) {
-		return state.isOf(LintBlocks.FUSED_STONE) || super.canCarveBlock(state, stateAbove);
+		return state.isOf(LintBlocks.FUSED_STONE) || state.isOf(LintBlocks.INDIGO_STONE) || state.isOf(LintBlocks.CORRUPT_GRASS) || state.isOf(LintBlocks.LIVELY_GRASS) || state.isOf(LintBlocks.FROSTED_GRASS) || state.isOf(LintBlocks.ASPHALT) || state.isOf(LintBlocks.CORRUPT_SAND) || state.isOf(LintBlocks.MYSTICAL_SAND) || state.isOf(LintBlocks.WHITE_SAND) || state.isOf(LintBlocks.ASH) || super.canCarveBlock(state, stateAbove);
```
Comment (ramidzkh) [inline src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java]: Make a tag at this point

File: src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java [hunk 2]
```diff
@@ -147,7 +147,7 @@ protected float getTunnelSystemWidth(Random random) {
 	protected boolean carveAtPoint(CarverContext context, LintCaveCarverConfig config, Chunk chunk, Function<BlockPos, Biome> posToBiome, BitSet carvingMask, Random random, BlockPos.Mutable pos, BlockPos.Mutable downPos, AquiferSampler sampler, MutableBoolean foundSurface) {
 		BlockState blockState = chunk.getBlockState(pos);
 		BlockState blockState2 = chunk.getBlockState(downPos.set(pos, Direction.UP));
-		if (blockState.isOf(LintBlocks.CORRUPT_GRASS) || blockState.isOf(LintBlocks.LIVELY_GRASS)) {
+		if (blockState.isOf(LintBlocks.CORRUPT_GRASS) || blockState.isOf(LintBlocks.LIVELY_GRASS) || blockState.isOf(LintBlocks.FROSTED_GRASS)) {
```
Comment (ramidzkh) [inline src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java]: Tag here too

**Review by ramidzkh — CHANGES_REQUESTED** [review]
Could you also fix that once place in structures where it's using the legacy method and putting structure void everywhere?

File: src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java (hunk 1 above)
Comment (valoeghese) [reply src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java]: Firstly, this doesn't match vanilla behaviour. This is what needs to be done:
- For the sand/gravel like blocks, you need `&& !stateAbove.getFluidState().isIn(FluidTags.WATER)`
- Secondly, don't carve Asphalt or Ash. Dawn shardlands doesn't need caves. It's a hecking floating island it's thin enough.
-  You can remove Super.canCarveBlock at this point because we don't use vanilla blocks.
- Finally, remove the grass from this method. Vanilla doesn't touch grass here.

File: src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java (hunk 2 above)
Comment (valoeghese) [reply src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java]: Alternatively `use DirtLikeBlock.isLintGrass()`

File: src/main/java/me/hydos/lint/world/carver/LintConfiguredCarvers.java [hunk 3]
```diff
@@ -19,7 +19,14 @@
...
+import net.minecraft.util.math.floatprovider.ConstantFloatProvider;
+import net.minecraft.util.registry.BuiltinRegistries;
+import net.minecraft.util.registry.Registry;
+import net.minecraft.world.gen.YOffset;
+import net.minecraft.world.gen.carver.ConfiguredCarver;
+import net.minecraft.world.gen.heightprovider.BiasedToBottomHeightProvider;
+
 public interface LintConfiguredCarvers {
-//	ConfiguredCarver<CarverConfig> CAVE = Registry.register(BuiltinRegistries.CONFIGURED_CARVER, Lint.id("nebulaes_bane"), LintCaveCarver.INSTANCE.configure(new ProbabilityConfig(0.09F)));
+	ConfiguredCarver<LintCaveCarverConfig> CAVE = Registry.register(BuiltinRegistries.CONFIGURED_CARVER, Lint.id("nebulaes_bane"), LintCaveCarver.CAVE.configure(new LintCaveCarverConfig(BiasedToBottomHeightProvider.create(YOffset.fixed(0), YOffset.fixed(127), 8), ConstantFloatProvider.create(0.5F), YOffset.aboveBottom(10), false, ConstantFloatProvider.create(0.5F), ConstantFloatProvider.create(0.5F), ConstantFloatProvider.create(-0.7F))));
```
Comment (valoeghese) [inline src/main/java/me/hydos/lint/world/carver/LintConfiguredCarvers.java:31]: what are all these new parameters

**Review by valoeghese — CHANGES_REQUESTED** [review]

**Comment by sylv256** [comment]
i'll finish doing this once i'm like halfway done with #103

File: src/main/java/me/hydos/lint/world/carver/LintConfiguredCarvers.java (hunk 3 above)
Comment (sylv256) [reply src/main/java/me/hydos/lint/world/carver/LintConfiguredCarvers.java:31]: This is the new 1.17 cavegen

File: src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java (hunk 1 above)
Comment (sylv256) [reply src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java]: If I remove the grass from this method, caves don't break the surface.

Comment (valoeghese) [reply src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java]: Okay so grass is allowed it seems. I fixed 1,2,3 of my points so this is fine

**Comment by sylv256** [comment]
i already ahve the changes locally i forgot to push lol

**Review by valoeghese — APPROVED** [review]

**Comment by valoeghese** [comment]
> i already ahve the changes locally i forgot to push lol

He Forgor 💀

**Comment by valoeghese** [comment]
Can you merge with my changes then and push? Getting this merged would be nice

**Comment by sylv256** [comment]
i'm trying out custom tags
also i have tons of refactors

**Comment by sylv256** [comment]
fixed (with block tags, of course!)

**Comment by sylv256** [comment]
should i merge now?

**Comment by sylv256** [comment]
I put the grass, stone, and dirt in `grass.json`, `stone.json`, and `dirt.json` respectively. i'm using tags like @ramidzkh suggested.

File: src/main/resources/data/lint/tags/blocks/dirt.json [hunk 4]
```diff
@@ -0,0 +1,6 @@
+{
+  "require": false,
```
Comment (sylv256) [inline src/main/resources/data/lint/tags/blocks/dirt.json]: this should be "replace"

File: src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java [hunk 5]
```diff
@@ -131,12 +132,12 @@ public boolean carve(CarverContext carverContext, LintCaveCarverConfig caveCarve
...
 	@Override
 	public boolean shouldCarve(LintCaveCarverConfig config, Random random) {
-		return false;
+		return random.nextFloat() <= config.probability;
 	}
 
 	@Override
 	protected boolean canCarveBlock(BlockState state, BlockState stateAbove) {
-		return state.isOf(LintBlocks.FUSED_STONE) || super.canCarveBlock(state, stateAbove);
+		return (state.isIn(LintBlockTags.STONE) || state.isIn(LintBlockTags.DIRT) || state.isIn(LintBlockTags.GRASS)) && !stateAbove.getFluidState().isIn(FluidTags.WATER);
```
Comment (valoeghese) [inline src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java:140]: THis check is slightly wrong. The underwater check is for underwater type (sand/gravel) blocks.

File: src/main/java/me/hydos/lint/world/feature/CanopyTreeFeature.java [hunk 6]
```diff
@@ -99,7 +91,7 @@ private boolean generate(StructureWorldAccess world, Random random, BlockPos sta
 				// 1. Canopy Leaves
 				for (int dy = -5; dy < 0; ++dy) {
 					float dymod = dy + 3;
-					float r = dy == 0 ? 1.01f : 4 - 0.5f * dymod * (1 + 0.1f * dymod * dymod); // radius
+					float r = 4 - 0.5f * dymod * (1 + 0.1f * dymod * dymod); // radius
```
Comment (valoeghese) [inline src/main/java/me/hydos/lint/world/feature/CanopyTreeFeature.java:94]: oh lmao I didn't even see the redundant check

**Comment by sylv256** [comment]
:crab:

File: src/main/java/me/hydos/lint/world/layer/GenericBiomes.java [hunk 7]
```diff
@@ -27,20 +27,13 @@
 import net.minecraft.world.biome.layer.type.InitLayer;
 import net.minecraft.world.biome.layer.util.LayerRandomnessSource;
 
-public class GenericBiomes implements InitLayer {
+public record GenericBiomes(Registry<Biome> biomeRegistry,
```
Comment (valoeghese) [inline src/main/java/me/hydos/lint/world/layer/GenericBiomes.java:30]: what the fuck those were private without getters

**Review by valoeghese — CHANGES_REQUESTED** [review]
Only a few problems

File: src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java (hunk 5 above)
Comment (sylv256) [reply src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java:140]: I don't need to make sure caves don't spawn underwater?

File: src/main/java/me/hydos/lint/world/layer/GenericBiomes.java (hunk 7 above)
Comment (sylv256) [reply src/main/java/me/hydos/lint/world/layer/GenericBiomes.java:30]: intellijank warned me to change it to a record
